import type { Service, ServiceArea, Project } from '@/types'

export const SERVICES: Service[] = [
  {
    slug:      'custom-backyard-design',
    title:     'Custom Backyard Design',
    shortDesc: 'Your dream backyard, designed from scratch — personalized to your style and budget.',
    description: 'We design your dream backyard from scratch — personalized to your style, budget, and space. Our free design consultation includes a full walkthrough of materials, layout options, and estimated costs. No cookie-cutter designs. Every project is built for you.',
    icon:      '✏️',
    keywords:  ['backyard design reno', 'custom landscape design nevada', 'outdoor design sparks nv'],
    featured:  true,
  },
  {
    slug:      'full-backyard-installation',
    title:     'Full Backyard Installation',
    shortDesc: 'From empty lot to finished outdoor living space — we handle everything.',
    description: 'From an empty lot to a finished outdoor living space — we handle excavation, grading, hardscaping, planting, irrigation, and final cleanup. One team, start to finish.',
    icon:      '🏗️',
    keywords:  ['backyard installation reno', 'landscape installation nevada', 'full yard build sparks'],
    featured:  true,
  },
  {
    slug:      'hardscaping-patios',
    title:     'Hardscaping & Patios',
    shortDesc: 'Custom patios, walkways, retaining walls and driveways built to last.',
    description: 'Custom patios, walkways, retaining walls, driveways, and outdoor structures built with premium materials. Natural stone, pavers, concrete, and boulders.',
    icon:      '🪨',
    keywords:  ['patio installation reno', 'hardscaping nevada', 'retaining wall sparks'],
    featured:  true,
  },
  {
    slug:      'irrigation-systems',
    title:     'Irrigation Systems',
    shortDesc: 'Smart irrigation designed for Nevada\'s dry climate — saves water and money.',
    description: 'Professional drip and sprinkler system design and installation. We optimize water usage for Nevada\'s dry climate — saving you money on every water bill.',
    icon:      '💧',
    keywords:  ['irrigation system reno', 'drip system nevada', 'sprinkler installation sparks'],
    featured:  false,
  },
  {
    slug:      'xeriscaping',
    title:     'Xeriscaping',
    shortDesc: 'Beautiful, low-maintenance yards that thrive in Reno\'s dry climate.',
    description: 'Water-efficient landscape design using drought-resistant plants, decorative rock, and smart layout — perfect for Northern Nevada\'s hot, dry summers.',
    icon:      '🌵',
    keywords:  ['xeriscaping reno', 'drought resistant landscaping nevada', 'desert landscape sparks'],
    featured:  false,
  },
  {
    slug:      'sod-installation',
    title:     'Sod Installation',
    shortDesc: 'Instant green lawns for residential and commercial properties.',
    description: 'Instant, lush green lawns using high-quality sod suited for Nevada\'s soil and climate. Residential and commercial.',
    icon:      '🌿',
    keywords:  ['sod installation reno', 'lawn installation nevada', 'grass install sparks nv'],
    featured:  false,
  },
  {
    slug:      'outdoor-living-spaces',
    title:     'Outdoor Living Spaces',
    shortDesc: 'Fire pits, pergolas, outdoor kitchens — backyards you actually use.',
    description: 'Fire pits, seating areas, pergolas, outdoor kitchens, and lighting — so your backyard becomes a space you love to use every day.',
    icon:      '🔥',
    keywords:  ['outdoor living reno', 'fire pit installation nevada', 'pergola sparks nv'],
    featured:  false,
  },
  {
    slug:      'landscape-maintenance',
    title:     'Landscape Maintenance',
    shortDesc: 'Year-round maintenance to keep your yard looking its best.',
    description: 'Regular maintenance programs including mowing, trimming, seasonal cleanup, fertilization, and irrigation checks.',
    icon:      '✂️',
    keywords:  ['landscape maintenance reno', 'yard maintenance nevada', 'lawn care sparks nv'],
    featured:  false,
  },
]

export const SERVICE_AREAS: ServiceArea[] = [
  { city: 'Reno',            state: 'NV', slug: 'reno-nv',            keywords: ['landscaping reno nv', 'reno landscaper', 'reno backyard'],        featured: true  },
  { city: 'Sparks',          state: 'NV', slug: 'sparks-nv',          keywords: ['landscaping sparks nv', 'sparks landscaper', 'sparks backyard'],   featured: true  },
  { city: 'Washoe County',   state: 'NV', slug: 'washoe-county-nv',   keywords: ['washoe county landscaping', 'washoe valley yard'],                 featured: true  },
  { city: 'Verdi',           state: 'NV', slug: 'verdi-nv',           keywords: ['landscaping verdi nv', 'verdi yard'],                               featured: false },
  { city: 'Spanish Springs', state: 'NV', slug: 'spanish-springs-nv', keywords: ['landscaping spanish springs', 'spanish springs yard'],              featured: false },
  { city: 'South Reno',      state: 'NV', slug: 'south-reno-nv',      keywords: ['south reno landscaping', 'south reno backyard'],                   featured: false },
  { city: 'Somersett',       state: 'NV', slug: 'somersett-nv',       keywords: ['somersett landscaping', 'somersett yard reno'],                    featured: false },
  { city: 'Caughlin Ranch',  state: 'NV', slug: 'caughlin-ranch-nv',  keywords: ['caughlin ranch landscaping', 'caughlin yard'],                     featured: false },
  { city: 'Lake Tahoe',      state: 'NV', slug: 'lake-tahoe-nv',      keywords: ['lake tahoe landscaping', 'tahoe yard design'],                     featured: true  },
  { city: 'Incline Village', state: 'NV', slug: 'incline-village-nv', keywords: ['incline village landscaping', 'incline yard'],                     featured: false },
]

export const PROJECTS: Project[] = [
  {
    id:       '1',
    title:    'Modern Backyard Transformation',
    category: 'Full Installation',
    location: 'Reno, NV',
    imageUrl: '/images/imgs/IMG_0249.PNG',
    featured: true,
  },
  {
    id:       '2',
    title:    'Custom Patio & Hardscape',
    category: 'Hardscaping',
    location: 'Sparks, NV',
    imageUrl: '/images/imgs/IMG_0250.PNG',
    featured: true,
  },
  {
    id:       '3',
    title:    'Backyard Oasis Design',
    category: 'Custom Design',
    location: 'South Reno, NV',
    imageUrl: '/images/imgs/IMG_0251.PNG',
    beforeUrl: '/images/imgs/IMG_0252.PNG',
    featured: true,
  },
  {
    id:       '4',
    title:    'Desert Xeriscape Makeover',
    category: 'Xeriscaping',
    location: 'Reno, NV',
    imageUrl: '/images/imgs/IMG_0271.PNG',
    featured: false,
  },
  {
    id:       '5',
    title:    'Stone Walkway & Borders',
    category: 'Hardscaping',
    location: 'Sparks, NV',
    imageUrl: '/images/imgs/IMG_0272.PNG',
    featured: false,
  },
  {
    id:       '6',
    title:    'Front Yard Curb Appeal',
    category: 'Full Installation',
    location: 'Washoe County, NV',
    imageUrl: '/images/imgs/IMG_0273.PNG',
    featured: false,
  },
  {
    id:       '7',
    title:    'Retaining Wall & Landscaping',
    category: 'Hardscaping',
    location: 'Somersett, NV',
    imageUrl: '/images/imgs/IMG_0274.PNG',
    featured: false,
  },
  {
    id:       '8',
    title:    'Outdoor Living Space',
    category: 'Outdoor Living',
    location: 'Caughlin Ranch, NV',
    imageUrl: '/images/imgs/IMG_0275.PNG',
    featured: false,
  },
  {
    id:       '9',
    title:    'Lush Green Lawn Install',
    category: 'Sod Installation',
    location: 'Spanish Springs, NV',
    imageUrl: '/images/imgs/IMG_0276.PNG',
    featured: false,
  },
  {
    id:       '10',
    title:    'Complete Yard Renovation',
    category: 'Full Installation',
    location: 'Reno, NV',
    imageUrl: '/images/imgs/IMG_0294.PNG',
    featured: false,
  },
  {
    id:       '11',
    title:    'Custom Rock & Plant Design',
    category: 'Xeriscaping',
    location: 'Sparks, NV',
    imageUrl: '/images/imgs/IMG_1842.JPG',
    featured: false,
  },
  {
    id:       '12',
    title:    'Backyard Entertainment Area',
    category: 'Outdoor Living',
    location: 'South Reno, NV',
    imageUrl: '/images/imgs/IMG_1843.JPG',
    featured: false,
  },
  {
    id:       '13',
    title:    'Full Hardscape & Planting',
    category: 'Hardscaping',
    location: 'Reno, NV',
    imageUrl: '/images/imgs/IMG_1845.PNG',
    featured: false,
  },
  {
    id:       '14',
    title:    'Modern Desert Landscape',
    category: 'Custom Design',
    location: 'Sparks, NV',
    imageUrl: '/images/imgs/IMG_1846.PNG',
    featured: false,
  },
  {
    id:       '15',
    title:    'Premium Patio Build',
    category: 'Hardscaping',
    location: 'Incline Village, NV',
    imageUrl: '/images/imgs/IMG_1847.PNG',
    featured: false,
  },
  {
    id:       '16',
    title:    '3D Backyard Design Render',
    category: 'Custom Design',
    location: 'Reno, NV',
    imageUrl: '/images/renders/BBFF6E8F-BEC4-49E1-B5D9-5B372DB01B8F.PNG',
    featured: true,
  },
  {
    id:       '17',
    title:    'Landscape Design Concept',
    category: 'Custom Design',
    location: 'Sparks, NV',
    imageUrl: '/images/renders/IMG_0269.PNG',
    featured: false,
  },
  {
    id:       '18',
    title:    'Backyard Layout Plan',
    category: 'Custom Design',
    location: 'South Reno, NV',
    imageUrl: '/images/renders/IMG_0270.PNG',
    featured: false,
  },
  {
    id:       '19',
    title:    'Project Design Visualization',
    category: 'Custom Design',
    location: 'Reno, NV',
    imageUrl: '/images/renders/IMG_1844.JPG',
    featured: false,
  },
  {
    id:       '20',
    title:    'Complete Yard Concept',
    category: 'Custom Design',
    location: 'Sparks, NV',
    imageUrl: '/images/renders/IMG_1848.JPG',
    featured: false,
  },
]

export const COMPANY = {
  name:    'TerraNova Landscaping',
  phone:   process.env.NEXT_PUBLIC_PHONE    || '(775) 000-0000',
  email:   process.env.NEXT_PUBLIC_EMAIL    || 'info@terranovalandscapingnv.com',
  website: process.env.NEXT_PUBLIC_SITE_URL || 'https://terranovalandscapingnv.com',
  years:   15,
  tagline: 'Northern Nevada\'s Custom Landscaping Specialists',
  description: 'TerraNova Landscaping transforms outdoor spaces across Reno, Sparks, and Northern Nevada with 15 years of expert craftsmanship.',
}
